//************************************************************************************************************************************
//*******************************************************GRAFIK-TEST CLASSI***********************************************************
//************************************************************************************************************************************
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Teyfik
 */
public class Grafik extends javax.swing.JFrame {

    /**
     * Creates new form Grafik
     */
    public Grafik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bilgisayar_8 = new javax.swing.JButton();
        bilgisayar_6 = new javax.swing.JButton();
        bilgisayar_7 = new javax.swing.JButton();
        bilgisayar_4 = new javax.swing.JButton();
        bilgisayar_3 = new javax.swing.JButton();
        bilgisayar_5 = new javax.swing.JButton();
        bilgisayar_2 = new javax.swing.JButton();
        bilgisayar_1 = new javax.swing.JButton();
        oyuncu_1 = new javax.swing.JButton();
        oyuncu_8 = new javax.swing.JButton();
        oyuncu_6 = new javax.swing.JButton();
        oyuncu_7 = new javax.swing.JButton();
        oyuncu_5 = new javax.swing.JButton();
        oyuncu_2 = new javax.swing.JButton();
        oyuncu_4 = new javax.swing.JButton();
        oyuncu_3 = new javax.swing.JButton();
        bilgisayar_atilan = new javax.swing.JButton();
        oyuncu_atilan = new javax.swing.JButton();
        takip_cubugu = new javax.swing.JLabel();
        puani_kim_aldi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KART OYUNU");
        setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bilgisayar_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1128, 123, 115, 140));
        getContentPane().add(bilgisayar_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 123, 115, 140));
        getContentPane().add(bilgisayar_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 123, 115, 140));
        getContentPane().add(bilgisayar_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 123, 115, 140));
        getContentPane().add(bilgisayar_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 123, 115, 140));
        getContentPane().add(bilgisayar_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 123, 115, 140));
        getContentPane().add(bilgisayar_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 123, 115, 140));
        getContentPane().add(bilgisayar_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 123, 115, 140));

        oyuncu_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_1ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 583, 115, 140));

        oyuncu_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_8ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1128, 583, 115, 140));

        oyuncu_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_6ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 583, 115, 140));

        oyuncu_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_7ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(981, 583, 115, 140));

        oyuncu_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_5ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 583, 115, 140));

        oyuncu_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_2ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 583, 115, 140));

        oyuncu_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_4ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 583, 115, 140));

        oyuncu_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_3ActionPerformed(evt);
            }
        });
        getContentPane().add(oyuncu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 583, 115, 140));
        getContentPane().add(bilgisayar_atilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 373, 115, 140));
        getContentPane().add(oyuncu_atilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 373, 115, 140));
        getContentPane().add(takip_cubugu, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, 572, 45));
        getContentPane().add(puani_kim_aldi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 580, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static int adim = 1;
    private static Grafik grafik = new Grafik();
    private static Futbolcu kullanici_secilen_futbolcu = null;
    private static Basketbolcu kullanici_secilen_basketbolcu = null;
    private static Kullanici kullanici = new Kullanici("123456", "Kullanıcı", 0);
    private static Bilgisayar bilgisayar = new Bilgisayar("123457", "Bilgisayar", 0);
    private static JButton esit_olan_futbolcu_bilgisayar = new JButton();
    private static JButton esit_olan_futbolcu_kullanici = new JButton();
    private static JButton esit_olan_basketbolcu_bilgisayar = new JButton();
    private static JButton esit_olan_basketbolcu_kullanici = new JButton();

    //ESIT OLAN VE GERI ALINMASI GEREKEN FUTBOLCU KARTLARINI BIR SONRAKI BUTON TIKLAMASINDA GERI CEKER
    public void esitleri_goster_futbolcu() {
        if (esit_olan_futbolcu_bilgisayar != null && esit_olan_futbolcu_kullanici != null) {
            esit_olan_futbolcu_bilgisayar.setVisible(true);
            esit_olan_futbolcu_kullanici.setVisible(true);
        }
    }

    //ESIT OLAN VE GERI CEKILMESI GEREKEN BASKETBOLCU KARTLARINI BIR SONRAKI BUTON TIKLAMASINDA GERI CEKER
    public void esitleri_goster_basketbolcu() {
        if (esit_olan_basketbolcu_bilgisayar != null && esit_olan_basketbolcu_kullanici != null) {
            esit_olan_basketbolcu_bilgisayar.setVisible(true);
            esit_olan_basketbolcu_kullanici.setVisible(true);
        }
    }

    //FUTBOLCU KIYASLAMASINDA PUAN EKLEYEN METODLAR
    private void bilgisayar_kazandi_futbolcu(int bilgisayar_kart_indexi, int kullanici_kart_indexi) {
        bilgisayar.setSkor(bilgisayar.getSkor() + 10);
        bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
        kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
        puani_kim_aldi.setText("Bilgisayar  10   Puan Aldı      Kullanıcı Puanı : "+kullanici.getSkor()+"  Bilgisayar Puanı : "+bilgisayar.getSkor());
        adim++;
    }

    private void kullanici_kazandi_futbolcu(int bilgisayar_kart_indexi, int kullanici_kart_inedxi) {
        kullanici.setSkor(kullanici.getSkor() + 10);
        bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
        kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_inedxi).setKart_kullanildimi(true);
        puani_kim_aldi.setText("Kullanıcı   10   Puan Aldı       Kullanıcı Puanı : "+kullanici.getSkor()+"  Bilgisayar Puanı : "+bilgisayar.getSkor());
        adim++;
    }

    //BASKETBOLCU KIYASLAMASINDA PUAN EKLEYEN METODLAR
    private void kullanici_kazandi_basketbolcu(int bilgisayar_kart_indexi,int kullanici_kart_indexi){
        kullanici.setSkor(kullanici.getSkor()+10);
        bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
        kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
        puani_kim_aldi.setText("Kullanıcı   10   Puan Aldı       Kullanıcı Puanı : "+kullanici.getSkor()+"  Bilgisayar Puanı : "+bilgisayar.getSkor());
        adim++;
        
    }
    private void bilgisayar_kazandi_basketbolcu(int bilgisayar_kart_indexi,int kullanici_kart_indexi){
        bilgisayar.setSkor(bilgisayar.getSkor()+10);
        bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
        kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
        puani_kim_aldi.setText("Bilgisayar  10   Puan Aldı      Kullanıcı Puanı : "+kullanici.getSkor()+"  Bilgisayar Puanı : "+bilgisayar.getSkor());
        adim++;
    }   

    //************************************************************************************************************************
    //*******************************************FUTBOLCUNUN SON KARTINI KIYASLAR*********************************************
    //************************************************************************************************************************
    private void son_kart_futbolcu() {
        while (true) {
            int pozisyon = (int) (Math.random() * 3);
            if (kullanici_secilen_futbolcu != null) {
                Futbolcu bilgisayar_secilen_futbolcu = bilgisayar.kart_sec_futbolcu();
                //BILGISAYARIN HANGI BUTONDAKI KARTI SECTIGINI TESPIT EDER
                JButton bilgisayar_secilen_buton = new JButton();
                if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_1.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_1;
                } else if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_2.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_2;
                } else if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_3.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_3;
                } else {
                    bilgisayar_secilen_buton = bilgisayar_4;
                }
                //BURADA BILGISAYAR KARTI ORTAYA ATAR
                bilgisayar_secilen_buton.setVisible(false);
                bilgisayar_atilan.setIcon(bilgisayar_secilen_buton.getIcon());

                //BURADA KULLANICI VE BILGISAYARIN SECILEN KARTLARI KIYASLANIR
                int kullanici_kart_indexi = kullanici.getFutbolcu_kart_listesi().indexOf(kullanici_secilen_futbolcu);
                int bilgisayar_kart_indexi = bilgisayar.getFutbolcu_kart_listesi().indexOf(bilgisayar_secilen_futbolcu);
                //***************************************************************************************************************************
                //***************************************************************************************************************************
                if (pozisyon == 0) {
                    //PENALTI
                    if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //SERBEST VURUS
                            if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN KALECIYLE KARSI KARSIYA KIYASLANIR
                                if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //KALECIYLE KARSI KARSIYA
                            if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN SERBEST VURUS KIYASLANIR
                                if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                    //KULLANICI PUAN ALIR
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }
                }
                //***************************************************************************************************************************
                //***************************************************************************************************************************
                else if (pozisyon == 1) {
                    //SERBEST VURUS
                    if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //PENALTI
                            if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN KALECIYLE KARSI KARSIYA KIYASLANIR
                                if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //KALECIYLE KARSI KARSIYA
                            if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN PENALTI KIYASLANIR
                                if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }

                }
                //***************************************************************************************************************************
                //***************************************************************************************************************************
                else {
                    //KALECIYLE KARSI KARSIYA
                    if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //SERBEST VURUS
                            if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN PENALTI KIYASLANIR
                                if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;

                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //PENALTI
                            if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN SERBEST VURUS KIYASLANIR
                                if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                    //KULLANICI PUAN ALIR
                                    kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;

                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }
                }

            }
        }
    }
    //************************************************************************************************************************
    //******************************************BASKETBOLCUNUN SON KARTINI KIYASLAR*******************************************
    //************************************************************************************************************************
    private void son_kart_basketbolcu() {
        while (true) {
            int pozisyon = (int) (Math.random() * 3);
            if (kullanici_secilen_basketbolcu != null) {
                Basketbolcu bilgisayar_secilen_basketbolcu = bilgisayar.kart_sec_basketbolcu();
                //BILGISAYARIN HANGI BUTONDAKI KARTI SECTIGINI TESPIT EDER
                JButton bilgisayar_secilen_buton = new JButton();
                if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_5.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_5;
                } else if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_6.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_6;
                } else if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_7.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_7;
                } else {
                    bilgisayar_secilen_buton = bilgisayar_8;
                }
                //BURADA BILGISAYAR KARTI ORTAYA ATAR
                bilgisayar_secilen_buton.setVisible(false);
                bilgisayar_atilan.setIcon(bilgisayar_secilen_buton.getIcon());

                //BURADA KULLANICI VE BILGISAYARIN SECILEN KARTLARI KIYASLANIR
                int kullanici_kart_indexi = kullanici.getBasketbolcu_kart_listesi().indexOf(kullanici_secilen_basketbolcu);
                int bilgisayar_kart_indexi = bilgisayar.getBasketbolcu_kart_listesi().indexOf(bilgisayar_secilen_basketbolcu);
                //************************************************************************************************************************
                //************************************************************************************************************************
                if (pozisyon == 0) {
                    //IKILIK
                    if (kullanici_secilen_basketbolcu.getIkilik() > bilgisayar_secilen_basketbolcu.getIkilik()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_basketbolcu.getIkilik() < bilgisayar_secilen_basketbolcu.getIkilik()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //SERBEST ATIS
                            if (kullanici_secilen_basketbolcu.getSerbest_atis() > bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getSerbest_atis() < bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN UCLUK KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getUcluk() > bilgisayar_secilen_basketbolcu.getUcluk()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getUcluk() < bilgisayar_secilen_basketbolcu.getUcluk()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //UCLUK
                            if (kullanici_secilen_basketbolcu.getUcluk() > bilgisayar_secilen_basketbolcu.getUcluk()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getUcluk() < bilgisayar_secilen_basketbolcu.getUcluk()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN SERBEST ATIS KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getSerbest_atis() > bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                    //KULLANICI PUAN ALIR
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getSerbest_atis() < bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }
                } 
                //**************************************************************************************************************************
                //**************************************************************************************************************************
                else if (pozisyon == 1) {
                    //SERBEST ATIS
                    if (kullanici_secilen_basketbolcu.getSerbest_atis() > bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_basketbolcu.getSerbest_atis() < bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //IKILIK
                            if (kullanici_secilen_basketbolcu.getIkilik() > bilgisayar_secilen_basketbolcu.getIkilik()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getIkilik() < bilgisayar_secilen_basketbolcu.getIkilik()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN UCLUK KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getUcluk() > bilgisayar_secilen_basketbolcu.getUcluk()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getUcluk() < bilgisayar_secilen_basketbolcu.getUcluk()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //UCLUK
                            if (kullanici_secilen_basketbolcu.getUcluk() > bilgisayar_secilen_basketbolcu.getUcluk()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getUcluk() < bilgisayar_secilen_basketbolcu.getUcluk()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN IKILIK KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getIkilik() > bilgisayar_secilen_basketbolcu.getIkilik()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getIkilik() < bilgisayar_secilen_basketbolcu.getIkilik()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }

                }
                //***************************************************************************************************************************
                //***************************************************************************************************************************
                else {
                    //UCLUK
                    if (kullanici_secilen_basketbolcu.getUcluk() > bilgisayar_secilen_basketbolcu.getUcluk()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_basketbolcu.getUcluk() < bilgisayar_secilen_basketbolcu.getUcluk()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //YENI POZISYON SECILIR EN SONRA KALAN POZISYON KIYASLANIR
                        int pozisyon_2 = (int) (Math.random() * 2);
                        if (pozisyon_2 == 1) {
                            //SERBEST ATIS
                            if (kullanici_secilen_basketbolcu.getSerbest_atis() > bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getSerbest_atis() < bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN IKILIK KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getIkilik() > bilgisayar_secilen_basketbolcu.getIkilik()) {
                                    //KULLANICI PUAN ALIR 
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getIkilik() < bilgisayar_secilen_basketbolcu.getIkilik()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;

                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        } else {
                            //IKILIK
                            if (kullanici_secilen_basketbolcu.getIkilik() > bilgisayar_secilen_basketbolcu.getIkilik()) {
                                //KULLANICI PUAN ALIR
                                kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else if (kullanici_secilen_basketbolcu.getIkilik() < bilgisayar_secilen_basketbolcu.getIkilik()) {
                                //BILGISAYAR PUAN ALIR
                                bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                kartlar_bittimi();
                                break;
                            } else {
                                //SON KALAN OZELLIK OLAN SERBEST ATIS KIYASLANIR
                                if (kullanici_secilen_basketbolcu.getSerbest_atis() > bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                    //KULLANICI PUAN ALIR
                                    kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;
                                } else if (kullanici_secilen_basketbolcu.getSerbest_atis() < bilgisayar_secilen_basketbolcu.getSerbest_atis()) {
                                    //BILGISAYAR PUAN ALIR
                                    bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                                    kartlar_bittimi();
                                    break;

                                } else {
                                    //BERABERLIK OLUR ANCAK SON KART OLDUGUNDAN KARTLARI KULLANILDI OLARAK AYARLANIR VE OYUN BITER
                                    kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(true);
                                    bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(true);
                                    grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış BERABERLİK");
                                    kartlar_bittimi();
                                    break;
                                }
                            }
                        }
                    }
                }

            }
        }
    }
    
    //************************************************************************************************************************
    //************************************************SON KART KONTROLU BITTI*************************************************
    //************************************************************************************************************************
    
    private void kartlar_bittimi() {
        int bilgisayar_basketci_sayisi = 0;
        int bilgisayar_futbolcu_sayisi = 0;
        int kullanici_futbolcu_sayisi = 0;
        int kullanici_basketci_sayisi = 0;
        for (int i = 0; i < 4; i++) {
            if (kullanici.getBasketbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_basketci_sayisi++;
            }
        }
        for (int i = 0; i < 4; i++) {
            if (kullanici.getFutbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_futbolcu_sayisi++;
            }
        }
        for (int i = 0; i < 4; i++) {
            if (bilgisayar.getBasketbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                bilgisayar_basketci_sayisi++;
            }
        }
        for (int i = 0; i < 4; i++) {
            if (bilgisayar.getFutbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                bilgisayar_futbolcu_sayisi++;
            }
        }
        if ((bilgisayar_basketci_sayisi == 4 && bilgisayar_futbolcu_sayisi == 4) && (kullanici_basketci_sayisi == 4 && kullanici_futbolcu_sayisi == 4)) {
            if (bilgisayar.getSkor() > kullanici.getSkor()) {
                JOptionPane.showMessageDialog(grafik, " Bilgisayarın Puanı : " + bilgisayar.getSkor()
                        + "\nOyuncu Puanı : " + kullanici.getSkor()
                        + "\nKazanan Bilgisayar...");
            } else if (bilgisayar.getSkor() < kullanici.getSkor()) {
                JOptionPane.showMessageDialog(grafik, " Bilgisayarın Puanı : " + bilgisayar.getSkor()
                        + "\nOyuncu Puanı : " + kullanici.getSkor()
                        + "\nKazanan Oyuncu...");
            } else {
                JOptionPane.showMessageDialog(grafik, " Bilgisayarın Puanı : " + bilgisayar.getSkor()
                        + "\nOyuncu Puanı : " + kullanici.getSkor()
                        + "\nBerabere...");
            }

        }
    }
    
    //futbolcuları kıyaslar
    private void futbolcu_kiyaslama() {
        //BURADA SIRANIN HANGI KART TIPINDE OLDUGU BELIRLENIR
        if (adim % 2 == 0) {
            JOptionPane.showMessageDialog(grafik, "LÜTFEN BASKETBOLCU SECIN");
            return;
        }
        JButton kullanici_secilen_buton = new JButton();
        if (kullanici_secilen_futbolcu.getIcon().equals(oyuncu_1.getIcon())) {
            kullanici_secilen_buton = oyuncu_1;
        } else if (kullanici_secilen_futbolcu.getIcon().equals(oyuncu_2.getIcon())) {
            kullanici_secilen_buton = oyuncu_2;
        } else if (kullanici_secilen_futbolcu.getIcon().equals(oyuncu_3.getIcon())) {
            kullanici_secilen_buton = oyuncu_3;
        } else {
            kullanici_secilen_buton = oyuncu_4;
        }
        //BURADA KULLANICI SECTIGI KARTI ORTAYA ATAR
        kullanici_secilen_buton.setVisible(false);
        oyuncu_atilan.setIcon(kullanici_secilen_buton.getIcon());

        //**********************************************************************************************
        //*************************************SON KARTMI KONTROLU**************************************
        //**********************************************************************************************
        int kullanici_basketbolcu_sayisi = 0;
        int kullanici_futbolcu_sayisi = 0;
        for (int i = 0; i < 4; i++) {
            if (kullanici.getFutbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_futbolcu_sayisi++;
            }
        }
        for (int i = 0; i < 4; i++) {
            if (kullanici.getBasketbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_basketbolcu_sayisi++;
            }
        }
        if (kullanici_basketbolcu_sayisi == 4 && kullanici_futbolcu_sayisi == 3) {
            son_kart_futbolcu();
            return;
        }
        //**********************************************************************************************
        //**********************************SON KARTMI KONTROLU BITIS***********************************
        //**********************************************************************************************    
        while (true) {
            int pozisyon = (int) (Math.random() * 3);
            if (kullanici_secilen_futbolcu != null) {
                //BILGISAYARA KARTI BURADA SECTIRIRIZ CUNKU ONCE KULLANICININ KART SECMESI LAZIM     
                Futbolcu bilgisayar_secilen_futbolcu = bilgisayar.kart_sec_futbolcu();

                //BILGISAYARIN HANGI BUTONDAKI KARTI SECTIGINI TESPIT EDER
                JButton bilgisayar_secilen_buton = new JButton();
                if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_1.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_1;
                } else if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_2.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_2;
                } else if (bilgisayar_secilen_futbolcu.getIcon().equals(bilgisayar_3.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_3;
                } else {
                    bilgisayar_secilen_buton = bilgisayar_4;
                }
                //BURADA BILGISAYAR KARTI ORTAYA ATAR
                bilgisayar_secilen_buton.setVisible(false);
                bilgisayar_atilan.setIcon(bilgisayar_secilen_buton.getIcon());

                //BURADA KULLANICI VE BILGISAYARIN SECILEN KARTLARI KIYASLANIR
                int kullanici_kart_indexi = kullanici.getFutbolcu_kart_listesi().indexOf(kullanici_secilen_futbolcu);
                int bilgisayar_kart_indexi = bilgisayar.getFutbolcu_kart_listesi().indexOf(bilgisayar_secilen_futbolcu);
                if (pozisyon == 0) {
                    //PENALTI
                    //BURADA KARTLAR KIYASLANIR KART KULLANILDIMI DEGERI ATANIR
                    if (kullanici_secilen_futbolcu.getPenalti() > bilgisayar_secilen_futbolcu.getPenalti()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getPenalti() < bilgisayar_secilen_futbolcu.getPenalti()) {
                        //BILGISAYAR PUAN ALIR                       
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);
                        bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_futbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_futbolcu_kullanici = kullanici_secilen_buton;

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Penaltı BERABERLİK ");
                        kartlar_bittimi();
                        break;
                    }
                } else if (pozisyon == 1) {
                    //SERBEST ATIS
                    if (kullanici_secilen_futbolcu.getSerbest_atis() > bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getSerbest_atis() < bilgisayar_secilen_futbolcu.getSerbest_atis()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);
                        bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_futbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_futbolcu_kullanici = kullanici_secilen_buton;
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Vuruş BERABERLİK ");
                        kartlar_bittimi();
                        break;
                    }
                } else {
                    //KALECIYLE KARSI KARSIYA
                    if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() > bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + kullanici_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (kullanici_secilen_futbolcu.getKaleciyle_karsi_karsiya() < bilgisayar_secilen_futbolcu.getKaleciyle_karsi_karsiya()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_futbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya Kazanan : " + bilgisayar_secilen_futbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        kullanici.getFutbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);
                        bilgisayar.getFutbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_futbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_futbolcu_kullanici = kullanici_secilen_buton;
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Kaleciyle Karşı Karşıya BERABERLİK ");
                        kartlar_bittimi();
                        break;
                    }
                    //BURADA KIYASLAMA BITER
                }
            }
        }
    }

    //BASKETBOLCULARI KIYASLAR
    private void basketbolcu_kiyaslama() {
        //BURADA SIRANIN HANGI KART TIPINDE OLDUGU BELIRLENIR
        if (adim % 2 == 1) {
            JOptionPane.showMessageDialog(grafik, "LÜTFEN FUTBOLCU SEÇİN");
            return;
        }
        JButton kullanici_secilen_buton = new JButton();

        if (kullanici_secilen_basketbolcu.getIcon().equals(oyuncu_5.getIcon())) {
            kullanici_secilen_buton = oyuncu_5;
        } else if (kullanici_secilen_basketbolcu.getIcon().equals(oyuncu_6.getIcon())) {
            kullanici_secilen_buton = oyuncu_6;
        } else if (kullanici_secilen_basketbolcu.getIcon().equals(oyuncu_7.getIcon())) {
            kullanici_secilen_buton = oyuncu_7;
        } else {
            kullanici_secilen_buton = oyuncu_8;
        }
        kullanici_secilen_buton.setVisible(false);
        oyuncu_atilan.setIcon(kullanici_secilen_buton.getIcon());

        //**********************************************************************************************
        //*************************************SON KARTMI KONTROLU**************************************
        //**********************************************************************************************
        int kullanici_basketbolcu_sayisi = 0;
        int kullanici_futbolcu_sayisi = 0;
        for (int i = 0; i < 4; i++) {
            if (kullanici.getFutbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_futbolcu_sayisi++;
            }
        }
        for (int i = 0; i < 4; i++) {
            if (kullanici.getBasketbolcu_kart_listesi().get(i).isKart_kullanildimi() == true) {
                kullanici_basketbolcu_sayisi++;
            }
        }
        if (kullanici_basketbolcu_sayisi == 3 && kullanici_futbolcu_sayisi == 4) {
            son_kart_basketbolcu();
            return;
        }
        //**********************************************************************************************
        //**********************************SON KARTMI KONTROLU BITIS***********************************
        //**********************************************************************************************
        
        while (true) {
            int pozisyon = (int) (Math.random() * 4);
            if (kullanici_secilen_basketbolcu != null) {
                //BILGISAYARA KARTI BURADA SECTIRIRIZ CUNKU ONCE KULLANICININ KART SECMESI LAZIM
                Basketbolcu bilgisayar_secilen_basketbolcu = bilgisayar.kart_sec_basketbolcu();

                //BIGISAYARIN HANGI BUTONDAKI KARTI SECTIGINI TESPIT EDER
                JButton bilgisayar_secilen_buton = new JButton();
                if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_5.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_5;
                } else if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_6.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_6;
                } else if (bilgisayar_secilen_basketbolcu.getIcon().equals(bilgisayar_7.getIcon())) {
                    bilgisayar_secilen_buton = bilgisayar_7;
                } else {
                    bilgisayar_secilen_buton = bilgisayar_8;
                }
                //BURADA BILGISAYAR KARTI ORTAYA ATAR
                bilgisayar_secilen_buton.setVisible(false);
                bilgisayar_atilan.setIcon(bilgisayar_secilen_buton.getIcon());

                //KARTLARI KIASYLAR KULLANILANLARI BELIRLER
                int bilgisayar_kart_indexi = bilgisayar.getBasketbolcu_kart_listesi().indexOf(bilgisayar_secilen_basketbolcu);
                int kullanici_kart_indexi = kullanici.getBasketbolcu_kart_listesi().indexOf(kullanici_secilen_basketbolcu);
                if (pozisyon == 1) {
                    //IKILIK
                    if (bilgisayar_secilen_basketbolcu.getIkilik() < kullanici_secilen_basketbolcu.getIkilik()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (bilgisayar_secilen_basketbolcu.getIkilik() > kullanici_secilen_basketbolcu.getIkilik()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);
                        kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_basketbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_basketbolcu_kullanici = kullanici_secilen_buton;
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik İkilik BERABERLİK ");
                        kartlar_bittimi();
                        break;

                    }

                } else if (pozisyon == 2) {
                    //UCLUK
                    if (bilgisayar_secilen_basketbolcu.getUcluk() < kullanici_secilen_basketbolcu.getUcluk()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (bilgisayar_secilen_basketbolcu.getUcluk() > kullanici_secilen_basketbolcu.getUcluk()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);
                        kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_basketbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_basketbolcu_kullanici = kullanici_secilen_buton;
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Üçlük BERABERLİK");
                        kartlar_bittimi();
                        break;

                    }
                } else {
                    //SERBEST ATIS
                    if (bilgisayar_secilen_basketbolcu.getSerbest_atis() < kullanici_secilen_basketbolcu.getSerbest_atis()) {
                        //KULLANICI PUAN ALIR
                        kullanici_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + kullanici_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else if (bilgisayar_secilen_basketbolcu.getSerbest_atis() > kullanici_secilen_basketbolcu.getSerbest_atis()) {
                        //BILGISAYAR PUAN ALIR
                        bilgisayar_kazandi_basketbolcu(bilgisayar_kart_indexi, kullanici_kart_indexi);

                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış Kazanan : " + bilgisayar_secilen_basketbolcu.getSpocu_isim());
                        kartlar_bittimi();
                        break;
                    } else {
                        //KIMSE PUAN ALMAZ KARTLAR ISE BIR SONRAKI TIKLAMADA IADE EDILIR
                        adim++;
                        bilgisayar.getBasketbolcu_kart_listesi().get(bilgisayar_kart_indexi).setKart_kullanildimi(false);
                        kullanici.getBasketbolcu_kart_listesi().get(kullanici_kart_indexi).setKart_kullanildimi(false);

                        esit_olan_basketbolcu_bilgisayar = bilgisayar_secilen_buton;
                        esit_olan_basketbolcu_kullanici = kullanici_secilen_buton;
                        grafik.takip_cubugu.setText("Kıyaslanan Özellik Serbest Atış BERABERLİK");
                        kartlar_bittimi();
                        break;
                    }
                }
            } else {

            }
        }
        //BURADA KIYASLAMA BITER
    }
    private void oyuncu_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_1ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_1.getIcon().equals(kullanici.getFutbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_futbolcu = kullanici.getFutbolcu_kart_listesi().get(i);
                break;
            }
        }
        futbolcu_kiyaslama();
        esitleri_goster_basketbolcu();
        esit_olan_basketbolcu_bilgisayar = null;
        esit_olan_basketbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_1ActionPerformed

    private void oyuncu_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_2ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_2.getIcon().equals(kullanici.getFutbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_futbolcu = kullanici.getFutbolcu_kart_listesi().get(i);
                break;
            }
        }
        futbolcu_kiyaslama();
        esitleri_goster_basketbolcu();
        esit_olan_basketbolcu_bilgisayar = null;
        esit_olan_basketbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_2ActionPerformed

    private void oyuncu_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_3ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_3.getIcon().equals(kullanici.getFutbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_futbolcu = kullanici.getFutbolcu_kart_listesi().get(i);
                break;
            }
        }
        futbolcu_kiyaslama();
        esitleri_goster_basketbolcu();
        esit_olan_basketbolcu_bilgisayar = null;
        esit_olan_basketbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_3ActionPerformed

    private void oyuncu_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_4ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_4.getIcon().equals(kullanici.getFutbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_futbolcu = kullanici.getFutbolcu_kart_listesi().get(i);
                break;
            }
        }
        futbolcu_kiyaslama();
        esitleri_goster_basketbolcu();
        esit_olan_basketbolcu_bilgisayar = null;
        esit_olan_basketbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_4ActionPerformed

    private void oyuncu_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_5ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_5.getIcon().equals(kullanici.getBasketbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_basketbolcu = kullanici.getBasketbolcu_kart_listesi().get(i);
                break;
            }
        }
        basketbolcu_kiyaslama();
        esitleri_goster_futbolcu();
        esit_olan_futbolcu_bilgisayar = null;
        esit_olan_futbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_5ActionPerformed

    private void oyuncu_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_6ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_6.getIcon().equals(kullanici.getBasketbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_basketbolcu = kullanici.getBasketbolcu_kart_listesi().get(i);
                break;
            }
        }
        basketbolcu_kiyaslama();
        esitleri_goster_futbolcu();
        esit_olan_futbolcu_bilgisayar = null;
        esit_olan_futbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_6ActionPerformed

    private void oyuncu_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_7ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_7.getIcon().equals(kullanici.getBasketbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_basketbolcu = kullanici.getBasketbolcu_kart_listesi().get(i);
                break;
            }
        }
        basketbolcu_kiyaslama();
        esitleri_goster_futbolcu();
        esit_olan_futbolcu_bilgisayar = null;
        esit_olan_futbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_7ActionPerformed

    private void oyuncu_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_8ActionPerformed
        for (int i = 0; i < 4; i++) {
            if (oyuncu_8.getIcon().equals(kullanici.getBasketbolcu_kart_listesi().get(i).getIcon())) {
                kullanici_secilen_basketbolcu = kullanici.getBasketbolcu_kart_listesi().get(i);
                break;
            }
        }
        basketbolcu_kiyaslama();
        esitleri_goster_futbolcu();
        esit_olan_futbolcu_bilgisayar = null;
        esit_olan_futbolcu_kullanici = null;
    }//GEN-LAST:event_oyuncu_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */     
        Futbolcu ronaldo = new Futbolcu(99, 99, 99, "Cristiano Ronaldo", "Malatyaspor","src\\Futbolcu\\ronaldo.jpg");
        Futbolcu messi = new Futbolcu(95, 94, 97, "Lionel Messi", "Malatyaspor","src\\Futbolcu\\messi.jpg");
        Futbolcu ibrahimovic = new Futbolcu(90, 88, 92, "Zlatan Ibrahimovic", "Malatyaspor","src\\Futbolcu\\ibrahimovic.jpg");
        Futbolcu neymar = new Futbolcu(98, 96, 96, "Neymar", "Malatyaspor","src\\Futbolcu\\neymar.jpg");
        Futbolcu sabri = new Futbolcu(100, 100, 100, "Sabri Sarioglu", "Malatyaspor","src\\Futbolcu\\sabri.jpg");
        Futbolcu özil = new Futbolcu(91, 80, 93, "Mesut Özil", "Malatyaspor","src\\Futbolcu\\özil.jpg");
        Futbolcu ramos = new Futbolcu(92, 85, 95, "Sergio Ramos", "Malatyaspor","src\\Futbolcu\\ramos.jpg");
        Futbolcu bale = new Futbolcu(94, 93, 90, "Gareth Bale", "Malatyaspor","src\\Futbolcu\\bale.jpg");
                
                
        Basketbolcu james = new Basketbolcu(100, 100, 100, "LeBron James", "Orduzuspor", "src\\Basketbolcu\\james.jpg");
        Basketbolcu jordan = new Basketbolcu(95, 93, 98, "Michael Jordan", "Orduzuspor", "src\\Basketbolcu\\jordan.jpg");
        Basketbolcu bryant = new Basketbolcu(80, 90, 96, "Kobe Bryant", "Orduzuspor", "src\\Basketbolcu\\bryant.jpg");
        Basketbolcu curry = new Basketbolcu(89, 96, 95, "Stephen Curry", "Orduzuspor", "src\\Basketbolcu\\curry.jpg");
        Basketbolcu cedi = new Basketbolcu(96, 89, 86, "Cedi Osman", "Orduzuspor", "src\\Basketbolcu\\cedi.jpg");
        Basketbolcu turkoglu = new Basketbolcu(91, 97, 87, "Hidayet Türkoğlu", "Orduzuspor", "src\\Basketbolcu\\turkoglu.jpg");
        Basketbolcu rose = new Basketbolcu(97, 92, 93, "Derrick Rose", "Orduzuspor", "src\\Basketbolcu\\rose.jpg");
        Basketbolcu russel = new Basketbolcu(90, 98, 80, "Bill Russel", "Orduzuspor", "src\\Basketbolcu\\russel.jpg");
        
        
        ArrayList<Futbolcu> futbolcular = new ArrayList<>();
        ArrayList<Basketbolcu> basketbolcular = new ArrayList<>();

        futbolcular.add(ronaldo);
        futbolcular.add(messi);
        futbolcular.add(ibrahimovic);
        futbolcular.add(neymar);
        futbolcular.add(sabri);
        futbolcular.add(özil);
        futbolcular.add(ramos);
        futbolcular.add(bale);

        basketbolcular.add(james);
        basketbolcular.add(jordan);
        basketbolcular.add(bryant);
        basketbolcular.add(curry);
        basketbolcular.add(cedi);
        basketbolcular.add(turkoglu);
        basketbolcular.add(rose);
        basketbolcular.add(russel);

        //*********************************************************************************************
        //************************************  KART DAGITIMI  ****************************************
        //*********************************************************************************************
        //BURADA RANDOM OLARAK FUTBOLCU KARTLARI KULLANICIYA VERİLMİSTİR
        int i = futbolcular.size();
        for (int j = 0; j < 4; j++) {
            ArrayList<Futbolcu> tmp = new ArrayList<>();
            int dagitici = (int) (Math.random() * i);
            tmp.add(futbolcular.get(dagitici));
            futbolcular.remove(dagitici);
            kullanici.futbolcuya_ekle(tmp);
            i--;

        }
        //BURADA KALAN KARTLAR BILGISAYARA ATANMISTIR
        for (int j = 0; j < 4; j++) {
            ArrayList<Futbolcu> tmp = new ArrayList<>();
            tmp.add(futbolcular.get(j));
            bilgisayar.futbolcuya_ekle(tmp);
        }
        //BURADA RANDOM OLARAK BASKETBOLCU KARTLARı KULLANICIYA VERİLMİSTİR
        i = basketbolcular.size();
        for (int j = 0; j < 4; j++) {
            ArrayList<Basketbolcu> tmp = new ArrayList<>();
            int dagitici = (int) (Math.random() * i);
            tmp.add(basketbolcular.get(dagitici));
            basketbolcular.remove(dagitici);
            kullanici.basketbolcuya_ekle(tmp);
            i--;

        }
        //BURADA KALAN KARTLAR BILGISAYARA ATANMISTIR
        for (int j = 0; j < 4; j++) {
            ArrayList<Basketbolcu> tmp = new ArrayList<>();
            tmp.add(basketbolcular.get(j));
            bilgisayar.basketbolcuya_ekle(tmp);
        }

        //BURADA PENCERE AKTİFLEŞTİRİLMİŞ VE BOYUT ÖLÇEKLENDİRME DEVRE DIŞI BIRAKILMIŞTIR
        grafik.setVisible(true);
        grafik.setResizable(false);

        grafik.getOyuncu_1().setIcon(kullanici.getFutbolcu_kart_listesi().get(0).getIcon());
        grafik.getOyuncu_2().setIcon(kullanici.getFutbolcu_kart_listesi().get(1).getIcon());
        grafik.getOyuncu_3().setIcon(kullanici.getFutbolcu_kart_listesi().get(2).getIcon());
        grafik.getOyuncu_4().setIcon(kullanici.getFutbolcu_kart_listesi().get(3).getIcon());

        grafik.getOyuncu_5().setIcon(kullanici.getBasketbolcu_kart_listesi().get(0).getIcon());
        grafik.getOyuncu_6().setIcon(kullanici.getBasketbolcu_kart_listesi().get(1).getIcon());
        grafik.getOyuncu_7().setIcon(kullanici.getBasketbolcu_kart_listesi().get(2).getIcon());
        grafik.getOyuncu_8().setIcon(kullanici.getBasketbolcu_kart_listesi().get(3).getIcon());

        grafik.getBilgisayar_1().setIcon(bilgisayar.getFutbolcu_kart_listesi().get(0).getIcon());
        grafik.getBilgisayar_2().setIcon(bilgisayar.getFutbolcu_kart_listesi().get(1).getIcon());
        grafik.getBilgisayar_3().setIcon(bilgisayar.getFutbolcu_kart_listesi().get(2).getIcon());
        grafik.getBilgisayar_4().setIcon(bilgisayar.getFutbolcu_kart_listesi().get(3).getIcon());

        grafik.getBilgisayar_5().setIcon(bilgisayar.getBasketbolcu_kart_listesi().get(0).getIcon());
        grafik.getBilgisayar_6().setIcon(bilgisayar.getBasketbolcu_kart_listesi().get(1).getIcon());
        grafik.getBilgisayar_7().setIcon(bilgisayar.getBasketbolcu_kart_listesi().get(2).getIcon());
        grafik.getBilgisayar_8().setIcon(bilgisayar.getBasketbolcu_kart_listesi().get(3).getIcon());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafik().setVisible(false);
            }
        });

    }

    public JButton getBilgisayar_1() {
        return bilgisayar_1;
    }

    public void setBilgisayar_1(JButton bilgisayar_1) {
        this.bilgisayar_1 = bilgisayar_1;
    }

    public JButton getBilgisayar_2() {
        return bilgisayar_2;
    }

    public void setBilgisayar_2(JButton bilgisayar_2) {
        this.bilgisayar_2 = bilgisayar_2;
    }

    public JButton getBilgisayar_3() {
        return bilgisayar_3;
    }

    public void setBilgisayar_3(JButton bilgisayar_3) {
        this.bilgisayar_3 = bilgisayar_3;
    }

    public JButton getBilgisayar_4() {
        return bilgisayar_4;
    }

    public void setBilgisayar_4(JButton bilgisayar_4) {
        this.bilgisayar_4 = bilgisayar_4;
    }

    public JButton getBilgisayar_5() {
        return bilgisayar_5;
    }

    public void setBilgisayar_5(JButton bilgisayar_5) {
        this.bilgisayar_5 = bilgisayar_5;
    }

    public JButton getBilgisayar_6() {
        return bilgisayar_6;
    }

    public void setBilgisayar_6(JButton bilgisayar_6) {
        this.bilgisayar_6 = bilgisayar_6;
    }

    public JButton getBilgisayar_7() {
        return bilgisayar_7;
    }

    public void setBilgisayar_7(JButton bilgisayar_7) {
        this.bilgisayar_7 = bilgisayar_7;
    }

    public JButton getBilgisayar_8() {
        return bilgisayar_8;
    }

    public void setBilgisayar_8(JButton bilgisayar_8) {
        this.bilgisayar_8 = bilgisayar_8;
    }

    public JButton getBilgisayar_atilan() {
        return bilgisayar_atilan;
    }

    public void setBilgisayar_atilan(JButton bilgisayar_atilan) {
        this.bilgisayar_atilan = bilgisayar_atilan;
    }

    public JButton getOyuncu_1() {
        return oyuncu_1;
    }

    public void setOyuncu_1(JButton oyuncu_1) {
        this.oyuncu_1 = oyuncu_1;
    }

    public JButton getOyuncu_2() {
        return oyuncu_2;
    }

    public void setOyuncu_2(JButton oyuncu_2) {
        this.oyuncu_2 = oyuncu_2;
    }

    public JButton getOyuncu_3() {
        return oyuncu_3;
    }

    public void setOyuncu_3(JButton oyuncu_3) {
        this.oyuncu_3 = oyuncu_3;
    }

    public JButton getOyuncu_4() {
        return oyuncu_4;
    }

    public void setOyuncu_4(JButton oyuncu_4) {
        this.oyuncu_4 = oyuncu_4;
    }

    public JButton getOyuncu_5() {
        return oyuncu_5;
    }

    public void setOyuncu_5(JButton oyuncu_5) {
        this.oyuncu_5 = oyuncu_5;
    }

    public JButton getOyuncu_6() {
        return oyuncu_6;
    }

    public void setOyuncu_6(JButton oyuncu_6) {
        this.oyuncu_6 = oyuncu_6;
    }

    public JButton getOyuncu_7() {
        return oyuncu_7;
    }

    public void setOyuncu_7(JButton oyuncu_7) {
        this.oyuncu_7 = oyuncu_7;
    }

    public JButton getOyuncu_8() {
        return oyuncu_8;
    }

    public void setOyuncu_8(JButton oyuncu_8) {
        this.oyuncu_8 = oyuncu_8;
    }

    public JButton getOyuncu_atilan() {
        return oyuncu_atilan;
    }

    public void setOyuncu_atilan(JButton oyuncu_atilan) {
        this.oyuncu_atilan = oyuncu_atilan;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilgisayar_1;
    private javax.swing.JButton bilgisayar_2;
    private javax.swing.JButton bilgisayar_3;
    private javax.swing.JButton bilgisayar_4;
    private javax.swing.JButton bilgisayar_5;
    private javax.swing.JButton bilgisayar_6;
    private javax.swing.JButton bilgisayar_7;
    private javax.swing.JButton bilgisayar_8;
    private javax.swing.JButton bilgisayar_atilan;
    private javax.swing.JButton oyuncu_1;
    private javax.swing.JButton oyuncu_2;
    private javax.swing.JButton oyuncu_3;
    private javax.swing.JButton oyuncu_4;
    private javax.swing.JButton oyuncu_5;
    private javax.swing.JButton oyuncu_6;
    private javax.swing.JButton oyuncu_7;
    private javax.swing.JButton oyuncu_8;
    private javax.swing.JButton oyuncu_atilan;
    private javax.swing.JLabel puani_kim_aldi;
    private javax.swing.JLabel takip_cubugu;
    // End of variables declaration//GEN-END:variables
}
